python /home/jennyw2/code/lerobot/src/lerobot/scripts/lerobot_train.py --dataset.repo_id=JennyWWW/splatsim_approach_lever_1path_basewrist --policy.type=pi05 --output_dir=./outputs/training/pi05_approach_lever_1path_basewrist --job_name=pi05_approach_lever_1path_basewrist --policy.repo_id=pi05_approach_lever_1path_basewrist --policy.pretrained_path=lerobot/pi05_base --policy.compile_model=false --policy.gradient_checkpointing=true --wandb.enable=true --policy.dtype=bfloat16 --steps=3000 --policy.scheduler_decay_steps=3000 --policy.device=cuda --batch_size=16 --policy.train_expert_only=true --policy.use_amp=true --save_freq=1000 --env.type=splatsim --env.task=upright_small_engine_new --env.camera_names='["base_rgb", "wrist_rgb"]' --env.fps=30 --eval.n_episodes=5 --eval.batch_size=1 --eval.use_async_envs=false --env.image_resize_mode=letterbox --eval_freq=1000

sleep 10

python /home/jennyw2/code/lerobot/src/lerobot/scripts/lerobot_train.py --dataset.repo_id=JennyWWW/splatsim_approach_lever_1path_base --policy.type=pi05 --output_dir=./outputs/training/pi05_approach_lever_1path_meanstate_quantileaction_base --job_name=pi05_approach_lever_1path_meanstate_quantileaction_base --policy.repo_id=pi05_approach_lever_1path_meanstate_quantileaction_base --policy.pretrained_path=lerobot/pi05_base --policy.compile_model=false --policy.gradient_checkpointing=true --wandb.enable=true --policy.dtype=bfloat16 --steps=3000 --policy.scheduler_decay_steps=3000 --policy.device=cuda --batch_size=16 --policy.train_expert_only=true --policy.use_amp=true --save_freq=1000 --env.type=splatsim --env.task=upright_small_engine_new --env.camera_names='["base_rgb"]' --env.fps=30 --eval.n_episodes=5 --eval.batch_size=1 --eval.use_async_envs=false --env.image_resize_mode=letterbox "--policy.normalization_mapping={\"STATE\": \"MEAN_STD\", \"ACTION\": \"QUANTILES\", \"VISUAL\": \"IDENTITY\"}" --eval_freq=1000

sleep 10

python /home/jennyw2/code/lerobot/src/lerobot/scripts/lerobot_train.py --dataset.repo_id=JennyWWW/splatsim_approach_lever_1path_base --policy.type=pi05 --output_dir=./outputs/training/pi05_approach_lever_1path_maxstate_quantileaction_base --job_name=pi05_approach_lever_1path_maxstate_quantileaction_base --policy.repo_id=pi05_approach_lever_1path_maxstate_quantileaction_base --policy.pretrained_path=lerobot/pi05_base --policy.compile_model=false --policy.gradient_checkpointing=true --wandb.enable=true --policy.dtype=bfloat16 --steps=3000 --policy.scheduler_decay_steps=3000 --policy.device=cuda --batch_size=16 --policy.train_expert_only=true --policy.use_amp=true --save_freq=1000 --env.type=splatsim --env.task=upright_small_engine_new --env.camera_names='["base_rgb"]' --env.fps=30 --eval.n_episodes=5 --eval.batch_size=1 --eval.use_async_envs=false --env.image_resize_mode=letterbox "--policy.normalization_mapping={\"STATE\": \"MIN_MAX\", \"ACTION\": \"QUANTILES\", \"VISUAL\": \"IDENTITY\"}" --eval_freq=1000
