# PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python /home/jennyw2/code/lerobot/src/lerobot/scripts/lerobot_train.py --dataset.repo_id=JennyWWW/splatsim_approach_lever_2_1path_basewrist --policy.type=pi05 --output_dir=./outputs/training/pi05_approach_lever_2_1path_basewrist --job_name=pi05_approach_lever_2_1path_basewrist --policy.repo_id=pi05_approach_lever_2_1path_basewrist --policy.pretrained_path=lerobot/pi05_base --policy.compile_model=false --policy.gradient_checkpointing=true --wandb.enable=true --policy.dtype=bfloat16 --steps=3000 --policy.scheduler_decay_steps=3000 --policy.device=cuda --batch_size=16 --policy.train_expert_only=true --policy.use_amp=true --save_freq=1000 --env.type=splatsim --env.task=upright_small_engine_new --env.camera_names='["base_rgb", "wrist_rgb"]' --env.fps=30 --eval.n_episodes=5 --eval.batch_size=1 --eval.use_async_envs=false --env.image_resize_mode=letterbox --eval_freq=1000

# sleep 10

# python /home/jennyw2/code/lerobot/src/lerobot/scripts/lerobot_train.py --dataset.repo_id=JennyWWW/splatsim_approach_lever_2_1path_base --policy.type=pi05 --output_dir=./outputs/training/pi05_approach_lever_2_1path_base --job_name=pi05_approach_lever_2_1path_base --policy.repo_id=pi05_approach_lever_2_1path_basew --policy.pretrained_path=lerobot/pi05_base --policy.compile_model=false --policy.gradient_checkpointing=true --wandb.enable=true --policy.dtype=bfloat16 --steps=3000 --policy.scheduler_decay_steps=3000 --policy.device=cuda --batch_size=16 --policy.train_expert_only=true --policy.use_amp=true --save_freq=1000 --env.type=splatsim --env.task=upright_small_engine_new --env.camera_names='["base_rgb"]' --env.fps=30 --eval.n_episodes=5 --eval.batch_size=1 --eval.use_async_envs=false --env.image_resize_mode=letterbox --eval_freq=1000

# sleep 10

# python /home/jennyw2/code/lerobot/src/lerobot/scripts/lerobot_train.py --dataset.repo_id=JennyWWW/splatsim_approach_lever_2_1path_wrist --policy.type=pi05 --output_dir=./outputs/training/pi05_approach_lever_2_1path_wrist --job_name=pi05_approach_lever_2_1path_wrist --policy.repo_id=pi05_approach_lever_2_1path_wrist --policy.pretrained_path=lerobot/pi05_base --policy.compile_model=false --policy.gradient_checkpointing=true --wandb.enable=true --policy.dtype=bfloat16 --steps=3000 --policy.scheduler_decay_steps=3000 --policy.device=cuda --batch_size=16 --policy.train_expert_only=true --policy.use_amp=true --save_freq=1000 --env.type=splatsim --env.task=upright_small_engine_new --env.camera_names='["wrist_rgb"]' --env.fps=30 --eval.n_episodes=5 --eval.batch_size=1 --eval.use_async_envs=false --env.image_resize_mode=letterbox --eval_freq=1000

# sleep 10

# python /home/jennyw2/code/lerobot/src/lerobot/scripts/lerobot_train.py --dataset.repo_id=JennyWWW/splatsim_approach_lever_2_1path_stretch_basewrist --policy.type=diffusion --output_dir=./outputs/training/diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_basewrist --job_name=diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_basewrist --policy.repo_id=diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_basewrist --eval_freq=25000 --save_freq=25000 --wandb.enable=true --steps=75000 --policy.device=cuda --batch_size=32 --policy.vision_backbone=resnet18 --policy.pretrained_backbone_weights=null --policy.use_group_norm=true "--policy.crop_shape=[224, 224]" --policy.crop_is_random=false --env.type=splatsim --env.task=upright_small_engine_new --env.camera_names='["base_rgb", "wrist_rgb"]' --env.fps=30 --eval.n_episodes=5 --eval.batch_size=1 --eval.use_async_envs=false --policy.optimizer_lr=1e-5 --env.image_resize_mode=stretch --policy.use_separate_rgb_encoder_per_camera=true

# sleep 10

# python /home/jennyw2/code/lerobot/src/lerobot/scripts/lerobot_train.py --dataset.repo_id=JennyWWW/splatsim_approach_lever_2_1path_stretch_base --policy.type=diffusion --output_dir=./outputs/training/diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_base --job_name=diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_base --policy.repo_id=diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_base --eval_freq=25000 --save_freq=25000 --wandb.enable=true --steps=75000 --policy.device=cuda --batch_size=32 --policy.vision_backbone=resnet18 --policy.pretrained_backbone_weights=null --policy.use_group_norm=true "--policy.crop_shape=[224, 224]" --policy.crop_is_random=false --env.type=splatsim --env.task=upright_small_engine_new --env.camera_names='["base_rgb"]' --env.fps=30 --eval.n_episodes=5 --eval.batch_size=1 --eval.use_async_envs=false --policy.optimizer_lr=1e-5 --env.image_resize_mode=stretch --policy.use_separate_rgb_encoder_per_camera=true

# sleep 10

# python /home/jennyw2/code/lerobot/src/lerobot/scripts/lerobot_train.py --dataset.repo_id=JennyWWW/splatsim_approach_lever_2_1path_stretch_wrist --policy.type=diffusion --output_dir=./outputs/training/diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_wrist --job_name=diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_wrist --policy.repo_id=diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_wrist --eval_freq=25000 --save_freq=25000 --wandb.enable=true --steps=75000 --policy.device=cuda --batch_size=32 --policy.vision_backbone=resnet18 --policy.pretrained_backbone_weights=null --policy.use_group_norm=true "--policy.crop_shape=[224, 224]" --policy.crop_is_random=false --env.type=splatsim --env.task=upright_small_engine_new --env.camera_names='["wrist_rgb"]' --env.fps=30 --eval.n_episodes=5 --eval.batch_size=1 --eval.use_async_envs=false --policy.optimizer_lr=1e-5 --env.image_resize_mode=stretch --policy.use_separate_rgb_encoder_per_camera=true

python /home/jennyw2/code/lerobot/src/lerobot/scripts/lerobot_train.py --dataset.repo_id=JennyWWW/splatsim_approachlever_2_1pth_stretch_basewrist --policy.type=diffusion --output_dir=./outputs/training/diffusion_approach_lever_2_1path_scratch_stretch_gn_basewrist --job_name=diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_basewrist --policy.repo_id=diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_basewrist --eval_freq=25000 --save_freq=25000 --wandb.enable=true --steps=75000 --policy.device=cuda --batch_size=32 --policy.vision_backbone=resnet18 --policy.pretrained_backbone_weights=null --policy.use_group_norm=true "--policy.crop_shape=[224, 224]" --policy.crop_is_random=false --env.type=splatsim --env.task=upright_small_engine_new --env.camera_names='["base_rgb", "wrist_rgb"]' --env.fps=30 --eval.n_episodes=5 --eval.batch_size=1 --eval.use_async_envs=false --policy.optimizer_lr=1e-5 --env.image_resize_mode=stretch --policy.use_separate_rgb_encoder_per_camera=true

sleep 10

python /home/jennyw2/code/lerobot/src/lerobot/scripts/lerobot_train.py --dataset.repo_id=JennyWWW/splatsim_approach_lever_2_1path_stretch_wrist --policy.type=diffusion --output_dir=./outputs/training/diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_wrist --job_name=diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_wrist --policy.repo_id=diffusion_approach_lever_2_1path_lr1e-5_scratch_stretch_gn_wrist --eval_freq=25000 --save_freq=25000 --wandb.enable=true --steps=75000 --policy.device=cuda --batch_size=32 --policy.vision_backbone=resnet18 --policy.pretrained_backbone_weights=null --policy.use_group_norm=true "--policy.crop_shape=[224, 224]" --policy.crop_is_random=false --env.type=splatsim --env.task=upright_small_engine_new --env.camera_names='["wrist_rgb"]' --env.fps=30 --eval.n_episodes=5 --eval.batch_size=1 --eval.use_async_envs=false --policy.optimizer_lr=1e-5 --env.image_resize_mode=stretch --policy.use_separate_rgb_encoder_per_camera=true
