#!/usr/bin/env bash
# PLAIN-COLLECTOR LINEAGE (05dag): 04dagpl + the stalled-handoff onset-ramp fix
# (rrt_path_utils strict_onset for any start_vel; tests/handoff_acceptance A2): standard HG-DAgger loop, NO dart/sw in the
# finetunes — the clean substrate the offline noise arms are applied to.
# Derived from 04dagsw_cmd.sh; original header: (Jenny 09-05): rerun the DAgger loop — per-round finetune +
# fresh intervention collection — with the calibrated DART noise (dn8) and the
# sw config (mask_hold_tail + selective_mask + pad-mask) carried into every
# per-round finetune, plus dose control (raw_mix=0.5: clean intervention
# frames kept alongside noised ones — the b3 substitution fix). No blends
# (SOURCE-ONLY mode); blends are generated by separate scripts now.
# Round 0 reuses the existing base checkpoint via skip-detection (tag-free name).
cd /home/jennyw2/code/lerobot

bash my_scripts/dagger_orchestrate_sweep.sh \
  --auto_create_source \
  --combination_pool= \
  --sweep_combinations_of=0 \
  --rerun_blends_from=10cl \
  --run_tag=10cl \
  --num_rounds=2 \
  --action_format=rel \
  --base_short=planar_3joint_12 \
  --blend_labels=dart \
  --cameras=state \
  --control_gui \
  --dag_short_override=planar_12 \
  --dagger_data_fraction=0.3 \
  --dagger_data_fraction_mode=exact \
  --dagger_skip_succeeded_in_prev_eval=true \
  --env_external_port=6001 \
  --env_profile=planar \
  --eval_benchmark=JennyWWW/eval_planar_3joint_benchmark \
  --exclude_gripper_from_state \
  --final_mode=finetune \
  --finetune_eval_freq=10000 \
  --finetune_extra_args='--optimizer.lr=1e-6 --dataset.multi_source_feature_intersection=true --dataset.dart_relabel=true --dataset.dart_self_relabel_pattern=_r_dag\d+$ --dataset.dart_state_noise_std=0 --dataset.dart_state_noise_schedule=/home/jennyw2/code/lerobot/my_scripts/paper_plots/tables_repro/analysis/noise_schedule_pooled_cl1_K2.json --dataset.dart_state_noise_scale=1.0 --dataset.dart_vel_noise_std=0.3 --dataset.dart_mask_hold_tail=true --dataset.dart_selective_mask=true --policy.do_mask_loss_for_padding=true' \
  --finetune_save_freq=10000 \
  --finetune_steps=10000 \
  --headless \
  --include_env_state_obs=true \
  --intermediate_mode=finetune \
  --intervention_extra_args='--intervention.max_cycles_per_scenario=5 --policy.shared_autonomy_config.rrt_ik_goal_selection=joint_distance --policy.shared_autonomy_config.rrt_num_ik_candidates=32 --policy.shared_autonomy_config.rrt_num_path_candidates_per_ik=5  --policy.shared_autonomy_config.rrt_max_path_attempts_per_ik=15  --policy.shared_autonomy_config.rrt_path_perturbation_scale=0.05   --policy.shared_autonomy_config.rrt_path_selection=ee_arc_length  --policy.shared_autonomy_config.rrt_path_score_joint_arc_weight=0.03   --policy.shared_autonomy_config.rrt_segment_at_sharp_corners=false   --policy.shared_autonomy_config.pre_jump_lookback.steps_min=50   --policy.shared_autonomy_config.pre_jump_lookback.steps_max=100   --policy.shared_autonomy_config.rrt_obstacle_clearance=0.02  --policy.shared_autonomy_config.rrt_self_collision_clearance=0.005 --policy.shared_autonomy_config.rrt_in_progress_obstacle_clearance=0.02 --policy.shared_autonomy_config.rrt_in_progress_self_collision_clearance=0.005 --policy.shared_autonomy_config.future_chunk.plan_fail_cooldown_ticks=1  --policy.shared_autonomy_config.rrt_diagnostic_log_pairs=first --policy.shared_autonomy_config.rrt_collision_detection=hybrid --policy.shared_autonomy_config.future_chunk.horizon_frames=8 --policy.shared_autonomy_config.future_chunk.obstacle_clearance=0.019 --policy.shared_autonomy_config.future_chunk.self_collision_clearance=0.005 --policy.shared_autonomy_config.future_chunk.rrt_obstacle_clearance=0.01 --policy.shared_autonomy_config.future_chunk.rrt_self_collision_clearance=0.005  --policy.shared_autonomy_config.rrt_smooth_iterations=200 --intervention.stuck_threshold_rad_per_tick=0.01 --intervention.stuck_consecutive_ticks=5 --policy.shared_autonomy_config.rrt_ik_skip_gripper_obstacle_pairs=false --intervention.policy_steps_between_rrt_min=200  --intervention.policy_steps_between_rrt_max=300 --intervention.policy_steps_before_rrt=600 --env.teleop_pad_short_episodes=false' \
  --intervention_n_episodes=100 \
  --intervention_sample_from_first=100 \
  --intervention_sample_seed=0 \
  --keep_sa_gui \
  --model=diff \
  --norm_mode=aggregated \
  --resume \
  --round0_extra_args='--policy.down_dims=[128,256,512] --dataset.observation_noise_std={"observation.state":0.01,"observation.environment_state":0.005} --eval_benchmark_loss_freq=5000 --eval_benchmark_loss_max_batches=32 --eval.n_episodes=100 --seed=0 --env.terminate_on_collision=true --env.episode_length=1000 --optimizer.lr=1e-5 --policy.normalize_env_state=true' \
  --skip_alias_step \
  --use_weighted_sampling \
  "$@"
